---
- name: Déploiement Automatisé d'un Environnement de Test
  hosts: builders
  become: yes
  vars:
    project_name: "webapp_demo"
    app_port: 8080
    db_password: "super_secret_password"

  tasks:
    - name: 1. Création du dossier du projet
      file:
        path: "/opt/environnements_test/{{ project_name }}"
        state: directory
        mode: '0755'

    - name: 2. Génération du fichier docker-compose.yml
      copy:
        dest: "/opt/environnements_test/{{ project_name }}/docker-compose.yml"
        content: |
          services:
            webapp:
              image: nginx:latest
              container_name: {{ project_name }}_web
              ports:
                - "{{ app_port }}:80"
              networks:
                - app_net

            database:
              image: mariadb:10.6
              container_name: {{ project_name }}_db
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: test_db
              networks:
                - app_net

          networks:
            app_net:
              driver: bridge

    - name: 3. Lancement de l'environnement (Docker Compose)
      command: docker compose up -d
      args:
        chdir: "/opt/environnements_test/{{ project_name }}"
      register: deploy_output

    - name: 4. Vérification du déploiement
      debug:
        msg: "L'application est déployée ! Accès via http://localhost:{{ app_port }}"
