---
- name: Configuration et Exécution des Tests
  hosts: runners
  become: yes
  vars:
    target_url: "http://192.168.20.11:8080"

  tasks:
    - name: 1. Installation des outils de test (Python + Requests)
      apt:
        name: 
          - python3-pip
          - python3-requests
        state: present

    - name: 2. Création du script de test
      copy:
        dest: /root/test_website.py
        mode: '0755'
        content: |
          import requests
          import sys

          url = "{{ target_url }}"
          print(f"Testing URL: {url}")

          try:
              response = requests.get(url, timeout=5)
              print(f"Status Code: {response.status_code}")
              
              if response.status_code == 200:
                  if "Welcome to nginx!" in response.text:
                      print("SUCCESS: Nginx page found.")
                      sys.exit(0)
                  else:
                      print("FAILURE: Content mismatch.")
                      sys.exit(1)
              else:
                  print("FAILURE: Bad status code.")
                  sys.exit(1)
          except Exception as e:
              print(f"CRITICAL: Could not connect to app. {e}")
              sys.exit(1)

    - name: 3. Exécution du test
      command: python3 /root/test_website.py
      register: test_result
      ignore_errors: yes 

    - name: 4. Affichage du rapport de test
      debug:
        msg: 
          - "----------------------------------------"
          - "RÉSULTAT DU TEST : {{ 'SUCCÈS' if test_result.rc == 0 else 'ÉCHEC' }}"
          - "Détails : {{ test_result.stdout }}"
          - "----------------------------------------"

    - name: 5. Arrêt d'urgence si le test échoue
      fail:
        msg: "Les tests ont échoué ! On arrête tout."
      when: test_result.rc != 0
