---
- name: Configuration de base des serveurs
  hosts: all_servers
  user: root 

  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation des paquets communs
      apt:
        name:
          - curl
          - git
          - htop
          - vim
          - net-tools
        state: present
    
    - name: Message de fin
      debug:
        msg: "Le serveur {{ inventory_hostname }} est à jour et prêt !"
